### ISSUE TITLE
--username should be mandatory for Android

### ISSUE THREAD

**Issue by dkovacevic** [wireapp/backup-export-tool#10]
Android exporter requires @username but --username is not flagged as mandatory and that made me both sad and clueless for more than an hour

Error 405 is returned by Wire BE in --username is not provided

**Comment by LukasForst** [comment]
![image](https://user-images.githubusercontent.com/14038818/126039103-b257f174-7f95-4604-9a19-486573356246.png)
I guess it got fixed lately, I'll make it mandatory in the code as well :)
